services:
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    working_dir: /app
    ports:
      - "${PORT_CLIENT}:3000"
    env_file:
      - .env
    depends_on:
      - server

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    working_dir: /app
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    volumes:
      - ./server/static:/app/static
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:8.2
    ports:
      - "${DB_EXTERNAL_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/data/db

  nginx:
    image: nginx:stable
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - server
      - client
